from enum import Enum


class Action(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class SignalStatus(str, Enum):
    PENDING = "PENDING"
    CONSUMED = "CONSUMED"
    EXPIRED = "EXPIRED"


class RejectionReason(str, Enum):
    """PROJECT.md Section 9.3. INTERNAL_ERROR is not in the Section 9.3 list
    but is required by the Section 9.4 failure-mode table (unhandled
    exception in the Risk Engine evaluation path)."""

    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    STALE_SIGNAL = "STALE_SIGNAL"
    SIGNAL_WAS_HOLD = "SIGNAL_WAS_HOLD"
    MAX_POSITIONS_REACHED = "MAX_POSITIONS_REACHED"
    MAX_EXPOSURE_REACHED = "MAX_EXPOSURE_REACHED"
    DAILY_LOSS_LIMIT_HIT = "DAILY_LOSS_LIMIT_HIT"
    CONSECUTIVE_LOSS_PAUSE = "CONSECUTIVE_LOSS_PAUSE"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    KILLSWITCH_ACTIVE = "KILLSWITCH_ACTIVE"
    DUPLICATE_SIGNAL = "DUPLICATE_SIGNAL"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    INVALID_SIGNAL_SCHEMA = "INVALID_SIGNAL_SCHEMA"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    NO_POSITION_TO_EXIT = "NO_POSITION_TO_EXIT"


class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    FILLED = "FILLED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class PositionStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class AuditEventType(str, Enum):
    SIGNAL_RECEIVED = "SIGNAL_RECEIVED"
    SIGNAL_VALIDATION_FAILED = "SIGNAL_VALIDATION_FAILED"
    RISK_APPROVED = "RISK_APPROVED"
    RISK_REJECTED = "RISK_REJECTED"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_FAILED = "ORDER_FAILED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    POSITION_OPENED = "POSITION_OPENED"
    POSITION_CLOSED = "POSITION_CLOSED"
    KILLSWITCH_ENABLED = "KILLSWITCH_ENABLED"
    KILLSWITCH_DISABLED = "KILLSWITCH_DISABLED"
    CONFIG_CHANGED = "CONFIG_CHANGED"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
